#!/bin/sh
# compile other programs for GRAPE 
pc -O -o ../bin/tcfrontend3 tcfrontend3.p 
f77 -O -o ../bin/tcmaingap3 tcmaingap3.f 
f77 -O -o ../bin/tcmainca3 tcmainca3.f 
cc -O -o ../bin/coladjg3t coladjg3t.c
